# Database Configuration
POSTGRES_USER=census_user
POSTGRES_PASSWORD=census_password
POSTGRES_DB=census_db
POSTGRES_PORT=5432

# Redis Configuration
REDIS_PORT=6379

# Backend API Configuration
BACKEND_PORT=8000

# Frontend Configuration
FRONTEND_PORT=80
API_URL=http://localhost:8000/api

# Mapbox Token - Replace with your actual token
MAPBOX_TOKEN=pk.your_mapbox_token_here